export const GET_NODES = "GET_NODES"
export const GET_NODE_CHILD = "GET_NODE_CHILD"
export const CHANGE_HIDE = "CHANGE_HIDE"
export const DELETE_NODE = "DELETE_NODE"
export const ADD_NODE = "ADD_NODE"
export const CHANGE_NODE = "CHANGE_NODE"
export const ERROR = "ERROR"
